name: "Detect OpenAPI changes"
description: "Detects changed OpenAPI specs in a PR and outputs them as JSON."

inputs: {}

outputs:
  specs_json:
    description: "JSON array with the paths of changed OpenAPI specs"
    value: ${{ steps.detect.outputs.specs_json }}

runs:
  using: "composite"
  steps:
    - name: Checkout repository
      uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - name: Install jq
      shell: bash
      run: |
        sudo apt-get update
        sudo apt-get install -y jq

    - name: Detect changed OpenAPI specs
      id: detect
      shell: bash
      run: |
        set -e

        BASE_SHA="${{ github.event.pull_request.base.sha }}"
        HEAD_SHA="${{ github.event.pull_request.head.sha }}"

        echo "Base SHA: ${BASE_SHA}"
        echo "Head SHA: ${HEAD_SHA}"

        CHANGED_FILES=$(git diff --name-only "${BASE_SHA}" "${HEAD_SHA}" || true)

        echo "Changed files:"
        echo "${CHANGED_FILES}"

        # Keep only OpenAPI files under api/rest/**/openapi.yml|yaml
        SPECS=$(echo "${CHANGED_FILES}" \
          | grep -E '^api/rest/.*/openapi\.ya?ml$' \
          | sort -u || true)

        if [ -z "${SPECS}" ]; then
          echo "No OpenAPI specs changed."
          printf 'specs_json=%s\n' "[]" >> "$GITHUB_OUTPUT"
          exit 0
        fi

        echo "OpenAPI specs to validate and lint:"
        echo "${SPECS}"

        SPECS_JSON_COMPACT=$(printf '%s\n' "${SPECS}" | jq -R . | jq -s -c .)
        printf 'specs_json=%s\n' "${SPECS_JSON_COMPACT}" >> "$GITHUB_OUTPUT"
